### ISSUE TITLE
box-php should use newer PHP versions

### ISSUE THREAD

**Issue by hatchan** [wercker/box-php#9]
Currently the following version are installed:

- 5.3.28
- 5.4.28
- 5.5.11

The following versions are the latest supported:

- 5.4.36
- 5.5.20
- 5.6.4

TODO: 

- Remove 5.3 
- Add 5.6
- Bump major version

**Comment by ianbytchek** [comment]
Can we have 5.6? It's been out for ages now. Is it possible to manually update the composer as well? Running `composer self-update` throws:

```
  [Composer\Downloader\FilesystemException]                                                               
  Filesystem exception:                                                                                   
  Composer update failed: the "/home/ubuntu/.phpenv/versions/5.5/bin/composer" file could not be written  
```

Doing it with sudo gives:

```
sudo: composer: command not found
```

I'm obviously not doing something right.

**Comment by hatchan** [comment]
We're working on a update. In the mean time, can you check the permissions of the file: `/home/ubuntu/.phpenv/versions/5.5/bin/composer`.

Sudo doesn't work because php-env changes the PATH, these changes are lost when using sudo. You can try to add a `-E` to sudo to prevent sudo from changing you environment.
